on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ESP-IDF
      uses: espressif/idf-ci-action@v1
      with:
        esp-idf-version: 'v4.3'

    - name: Build ESP-IDF image
      run: |
        export IDF_PATH=$RUNNER_WORKSPACE/esp-idf
        export PATH=$IDF_PATH/tools:$PATH
        idf.py build